#channels:
#  - conda-forge
dependencies:
  - python>=3.5
  #- sphinx>=1.4  # Get WIP version of sphinx with MD stuff
  - pip
  - pandoc
  - nbconvert
  - ipykernel
  - pip:
    - sphinx
    - git+https://github.com/spatialaudio/nbsphinx.git@master
    #- sphinx-nbexamples  
    - git+https://github.com/Chilipp/sphinx-nbexamples.git@master # use app.add_css_file for sphinx >= 3.0
    - sphinx-gallery
    - sphinx-copybutton
    - recommonmark
    - m2r
