#channels:
#  - conda-forge
dependencies:
  - python>=3.5
  - sphinx
  - pip
  - pandoc
  - nbconvert
  - ipykernel
  - pip:
    - sphinx
    - nbsphinx
    #- sphinx-nbexamples
    - sphinx-gallery
    - sphinx-copybutton
    - recommonmark
    - m2r
