name: "Build Documentation"
on:
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs_wip/"
        build-command: "sphinx-build -b html . _build"