name: "📜 Documentation check"
on:
    - pull_request

jobs:
    docs:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # To be able to push refs to destination repo
            - name: Set up Python 🐍
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
                  cache: "pip"

            - name: Install dependencies 🏭
              run: |
                  python -m pip install --upgrade pip
                  pip install sphinx
                  pip install sphinx-book-theme
                  pip install sphinxemoji
                  pip install sphinx-copybutton
                  pip install ipython
                  pip install myst-parser
                  pip install myst-nb
                  pip install https://github.com/neuropsychology/neurokit/zipball/dev[test]

            - name: Build documentation 📜
              run: |
                  cd docs
                  sphinx-build -b html . _build
